<a href="https://colab.research.google.com/github/nanta765/nanta765/blob/main/2802548266_i_gusti_bagus_ananta_tusan_semadi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import time
print(time.ctime())

Thu Feb  6 02:40:29 2025


sesi satu


In [3]:
x = 1
x

1

In [4]:
x = x + 1
x

2

In [6]:
x = 1
y = x + 1
x = 2
y

2

In [7]:
import numpy as np

In [9]:
x = np.array([1,4,3])
x

array([1, 4, 3])

In [11]:
y = np.array([1,4,3])
y

array([1, 4, 3])

In [26]:
x = np.array([[1,4,3],[9,2,7]])
print(x)



[[1 4 3]
 [9 2 7]]


In [28]:
def my_adder(a, b, c):

  """
  function to sum three numbers
  Input: 3 numbers a, b, c
  Output: the sum of a, b, and c
  author:
  date:
  """


  #this is simulation
  out = a + b + c

  return out

In [29]:
my_adder(1, 2, 3)


6

In [30]:
def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
      status = 'Heat'
  elif temp > desired_temp + 5:
      status = 'AC'
  else:
      status = 'off'
  return status

In [35]:
status = my_thermo_stat(65,75)
print(status)


Heat


In [36]:
status = my_thermo_stat(75,65)
print(status)

AC


In [37]:
status = my_thermo_stat(65,63)
print(status)

off


In [39]:
x = 3
if x > 1 and x < 2:
  y = 2
elif x > 2 and x < 4:
    y = 4
else:
    y = 0
print(y)


4


In [40]:
x = 3
if 1 < x < 2:
  y = 2
elif 2 < x < 4:
  y = 4
else:
  y = 0
print(y)

4


In [43]:
val = float(input("masukan Nama anda : "))
val

masukan Nama anda : 9


9.0

In [42]:
val = input("masukan Nama anda : ") # Get the name as a string
print(val)  # Print the name

# If you need to input a number, change the prompt and keep the float conversion:
# num = float(input("masukan angka: "))
# print(num)

masukan Nama anda : ananta
ananta


In [47]:
def login():
    username = input("Username: ")
    password = input("Password: ")

    # Validasi username dan password
    if password != "Bn123":
        print("Username atau Password salah. Coba lagi.")
        return False
    return True

def calculate_final_score(uas, uts, asg):
    # Menghitung nilai akhir
    final_score = (0.5 * uas) + (0.3 * uts) + (0.2 * asg)
    return final_score

def determine_grade(final_score):
    # Menentukan grade berdasarkan nilai akhir
    if final_score >= 85:
        return 'A'
    elif final_score >= 70:
        return 'B'
    elif final_score >= 55:
        return 'C'
    elif final_score >= 40:
        return 'D'
    else:
        return 'E'

# Program utama
def main():
    # Login
    while not login():
        pass

    print("Login berhasil!")

    # Input nilai
    nama = input("Nama Siswa: ")

    while True:
        try:
            uas = int(input("Nilai UAS: "))
            uts = int(input("Nilai UTS: "))
            asg = int(input("Nilai ASG: "))
            break
        except ValueError:
            print("Harap masukkan angka yang valid!")

    # Menghitung nilai akhir
    final_score = calculate_final_score(uas, uts, asg)

    # Menentukan grade
    grade = determine_grade(final_score)

    # Menampilkan hasil
    print(f"\nNama Siswa: {nama}")
    print(f"Nilai UAS: {uas}")
    print(f"Nilai UTS: {uts}")
    print(f"Nilai ASG: {asg}")
    print(f"Nilai Akhir: {final_score:.2f}")
    print(f"Grade: {grade}")

if __name__ == "__main__":
    main()


Username: anantatusan
Password: Bn123
Login berhasil!
Nama Siswa: ananta
Nilai UAS: 80
Nilai UTS: 90
Nilai ASG: 70

Nama Siswa: ananta
Nilai UAS: 80
Nilai UTS: 90
Nilai ASG: 70
Nilai Akhir: 81.00
Grade: B
